### ISSUE TITLE
still want contributors?

### ISSUE THREAD

**Issue by jeremymuller** [sebpiq/WebPd#150]
Are you still looking for contributors? I'd like to work on adding the [array] object into this, as well as some others.

**Comment by sebpiq** [comment]
Hi @jeremymuller !

Yes of course ! 
Sorry for the slow answer, I was away for a bit. 
New objects would be amazing ! Several things though : 

- I first need to set things up so that it's easier for anyone to start working on the library. Right now dev setup is not straightforward. Also there's no docs explaining how to contribute new objects. 
- then also, maybe array is not the simplest thing to contribute. I haven't looked into it too much, but I believe the current webpd parser doesn't handle it, and there might be changes required in the core of the engine too in order to support pointers. So I'd recommend starting with something simpler

We can do this different ways then ! Either you can wait a couple of weeks / one month, until I sort everything out (I'm factoring in the fact that I have very little time to work on webpd these days), or if you're in a hurry, we can setup a call and I'll get you started. I prefer the first option since that would push me to write developer docs once and for all.

**Comment by sebpiq** [comment]
(let's switch back to discord if that's ok with you !)
