### ISSUE TITLE
Browser window wide

### ISSUE THREAD

**Issue by anibalzorrilla** [sebpiq/WebPd#58]
Dear friends, I did all like it is detailed in the readme file, but the windows of my browser remains white... in myPatch I put the PureData/3.audio.ex/A09... I use Chrome and Firefox, the last versions... I am in W7, here I share the console: 

![python_cmd](https://cloud.githubusercontent.com/assets/1836447/7442272/c78c8244-f0e0-11e4-8c17-8139a3daf775.gif)

**Comment by sebpiq** [comment]
Hi @anibalzorrilla and sorry for the slow answer. There is several problems here. I think everything works (Python and so on), but the patch you are using won't work for several reasons : 

1. it contains objects that don't exist in WebPd (because not implemented yet, or because they are abstractions), [tabwrite~], the abstraction [output~]. Remove them and the patch should load fine. If you check in the docs here : https://github.com/sebpiq/WebPd#a-patch-that-used-to-work-fine-with-webpd-has-stopped-working-after-i-modified-it this is somehow explained. If you open the browser console (ctrl+shift+i on linux and windows for Firefix and Chrome), you will see the error messages "unknown object [tabwrite~]" etc ...

2. even after you removed the unknown objects, the patch will load fine, but the frequencies of the oscillators are 0, which means that no sound will be heard. So you can either give it a default frequency (for example `[osc~ 220]`), or add some controls with JavaScript and a send object to be able to modify the frequencies and any other parameter you want from the web page (example here : http://sebpiq.github.io/WebPd/examples/phasor/, code here : https://github.com/sebpiq/WebPd/blob/master/examples/phasor/index.html)

In general when working with WebPd you should always check the console of your web browser to see if you are not using something that's not implemented yet, as only so little of the Pd functionalities are implemented. And in addition, as I illustrated above, there is a few things to keep in mind (you don't have a GUI like in Pd, so you should make sure your patch is properly initialized) which are proper to WebPd and the web in general. So hang on!

**Comment by anibalzorrilla** [comment]
Thanks a lot, I will try, best regards __________________________________________________
Aníbal N. Zorrilla
Pianista y compositor
Docente Investigador UNA, Departamento de Artes del Movimiento

Blog
Teoría y Práctica del RitmoInTAD

 
      De: Sebastien Piquemal <notifications@github.com>
 Para: sebpiq/WebPd <WebPd@noreply.github.com> 
CC: Aníbal Zorrilla <anibalzorrilla@yahoo.com.ar> 
 Enviado: Lunes, 4 de mayo, 2015 4:08:42
 Asunto: Re: [WebPd] Browser window wide (#58)
   
Closed #58.—

**Comment by sebpiq** [comment]
Cool. Do tell me if it still doesn't work, I can have a look.
