### ISSUE TITLE
[phasor~] is not an exact sawtooth

### ISSUE THREAD

**Issue by graphographer** [sebpiq/WebPd#69]
One can hear this in http://sebpiq.github.io/WebPd/examples/tabread-phasor/ at least on latest Firefox and Chrome. A similar thing happens in all my own patches too.

Just a guess, but maybe this is some sort of float precision issue? Thanks for all the hard work, though! I've been able to work around this by sticking to [line~] but I thought I'd point out this issue.

**Comment by sebpiq** [comment]
Yeah ... it's a "known issue". It is because the web audio API's
oscillators are band-limited, so basically the phasor is not a real phasor.
It is a bandlimited sawtooth, which looks like this :
http://arachnoid.com/maxima/graphics/sawtooth_wave_graph.png (but in the
other direction of course). I have another implementation which should
work, but doesn't in firefox (
https://github.com/sebpiq/WebPd/blob/master/lib/objects/dsp.js#L199) for
the moment, you'd better stick to line indeed ...

On Tue, Aug 25, 2015 at 12:00 AM, graphographer <notifications@github.com>
wrote:

> One can hear this in
> http://sebpiq.github.io/WebPd/examples/tabread-phasor/ at least on latest
> Firefox and Chrome. A similar thing happens in all my own patches too.
>
> Just a guess, but maybe this is some sort of float precision issue? Thanks
> for all the hard work, though! I've been able to work around this by
> sticking to [line~] but I thought I'd point out this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/69>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm
