### ISSUE TITLE
Skip unknown objects when parsing PD file

### ISSUE THREAD

**Issue by shamansir** [sebpiq/WebPd#85]
If I load some `*.pd` files in WebPd, it fails to parse them with a message like `Uncaught Error: unknown object env~` and actually seems to fail completely. Would you please wrap [this place](https://github.com/sebpiq/WebPd/blob/master/lib/core/Patch.js#L105) (I guess :) ) with `try/catch`, but yet inform user that object was not parsed. 

(Just extracted it from the mail :) )

**Comment by shamansir** [comment]
Implemented this in shamansir/WebPd@c35e273

**Comment by sebpiq** [comment]
I think it must throw an error if object is not valid, but you should be able to catch this particular error, and let other errors through. e.g. 

```
try {
} except (err) {
    if (err instanceof Pd.PatchLoadError) {
        handleError(err)
    } else throw err
}
```

On the other hand, you are right that it should catch all errors in a list so that the patch is fully loaded even though there are errors (https://github.com/shamansir/WebPd/commit/c35e273#diff-2aa3848da3dbbf622d74b9cb674db7b0R356)

**Comment by sebpiq** [comment]
I'll implement this now

**Comment by sebpiq** [comment]
Ok ... I realized why you need this exactly, and what I did is not going to help you.
Do I understand right that you need to display an object in red dashes when the object doesn't exist (like in Pd) ? In that case, you could for example register an `UnkownObject` external, and patch the `_preparePatch` to replace unknown objects with it. Something like : 

```javascript
Pd.registerExternal('UnknownObject', Pd.core.PdObject)

Pd._origPreparePatch = Pd._preparePatch
Pd._preparePatch = function(patch, patchData) {
  try { return Pd._origPreparePatch.apply(this, arguments) }
  catch (err) {
    if (err instanceof Pd.errors.PatchLoadError) {
      err.errorList.forEach(function(errElem) {
        if (errElem instanceof Pd.errors.UnkownObjectError) {
          patchData.nodes.forEach(function(nodeData) {
            if (nodeData.proto == errElem.objectType) {
              patch.createObject('UnknownObject')
          })
        }
      })
    } else throw err
  }
}
```

I am conscious this is rather ugly, but I really don't want to have "phantom" objects in WebPd. I think if an object doesn't exist that's an error, and this is the role of users (included a GUI library) to handle this error properly, so that way things are neatly separated. Now, with this commit, I gave you the possibility to do more fine-grained error handling, and I am sure you can manage with this :)

**Comment by shamansir** [comment]
> Do I understand right that you need to display an object in red dashes when the object doesn't exist (like in Pd) ?

Frankly I had a similar code of my own and now I replace it with `WebPd` for a better future. I had the special "object resolver" which I called even while parsing the file. But I forgot that I also need this for parsing stage in case of using WebPd, thank you a lot, I expect to manage that. 

> I am conscious this is rather ugly, but I really don't want to have "phantom" objects in WebPd.

Just in case, won't the objects that are unknown break the connection map, which has indexes that include "unknown objects"? Probably, if WebPd decides to skip objects like this and make patches work (in some way), it needs to fill in the gaps with something. On the other hand, I read it and it looks complicated. Broken patch is a broken patch in the end, we can't patch up the patch :).

**Comment by shamansir** [comment]
I got it, it sums up with `PatchLoadError` if contains something unknown. That's completely right!

**Comment by sebpiq** [comment]
:+1:
